# local database for dev. This file is ignored by git

development:
  adapter: postgresql
  database: db/development
  username: postgres
  password: spazzy
  host: localhost
  encoding: UTF8
  pool: 5
  timeout: 5000
